### ISSUE TITLE
Login with Email doesn't work because Lime does not accept passwords

### ISSUE THREAD

**Issue by KevinGay** [aPersonInNZ/lime-juicer#2]
Hi,

Thanks for taking the time to document all of this!

I'm in a tricky situation because I signed up for Lime using my email, and I was never asked to input a password. I just insert my email at the login screen, and they send a token directly to my email. I tried signing up with another email to verify that Lime never asks for a password. Were you able to get a token back through /login with an email? I just keep getting a 400 response.

I was able to get a token using my mobile number, but of course Lime treats the login with my mobile number as a separate account :( and I can't apply to be a juicer with that (mobile) account since my phone number is already linked to my existing (email) account.

Any help would be greatly appreciated. I'm trying to build a notification system that pings me whenever a scooter pops up within a few blocks of my house.

**Comment by W1MMER** [comment]
Oh nice! I will adjust this accordingly later. Yeah it seems like Lime don't use passwords anymore and instead use temporary tokens.

**Comment by W1MMER** [comment]
Have updated the login method in the latest commit :)

**Comment by KevinGay** [comment]
Awesome thank you so much!
